# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference_publication',
            old_name='reference_id',
            new_name='reference_publication_id',
        ),
    ]
