# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0002_auto_20170706_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference_publication',
            name='month',
        ),
    ]
