# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_remove_reference_publication_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferred_sets',
            name='reference_publication',
        ),
    ]
