# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0006_auto_20170706_1655'),
    ]

    operations = [
        migrations.RenameModel('Preferred_sets','Preferred_set')
    ]
