# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0007_auto_20170706_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferred_set',
            name='source_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_management.Source_type'),
        ),
    ]
