# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 18:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_management', '0008_preferred_set_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='constant_type',
            name='date_entered',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='constant_type',
            name='user_entered',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='molecular_state',
            name='date_entered',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='molecular_state',
            name='user_entered',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preferred_set',
            name='date_entered',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='preferred_set',
            name='user_entered',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reference_publication',
            name='date_entered',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reference_publication',
            name='user_entered',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='source_type',
            name='date_entered',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='source_type',
            name='user_entered',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='diatomic_constant',
            name='user_entered',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User_id',
        ),
    ]
