# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0009_auto_20170719_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecular_state',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
