# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0010_molecular_state_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_publication',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='reference_publication',
            name='url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
