# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0011_auto_20170725_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_publication',
            name='number',
            field=models.IntegerField(blank=True),
        ),
    ]
