# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0012_auto_20170725_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diatomic_constant',
            name='delta_minus',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='diatomic_constant',
            name='delta_plus',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='molecular_state',
            name='projected_angular_momentum',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='molecular_state',
            name='reflection_symmetry',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='molecular_state',
            name='total_angular_momentum',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='reference_publication',
            name='doi',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
