# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0013_auto_20170727_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diatomic_constant',
            name='delta_minus',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='diatomic_constant',
            name='delta_plus',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=20),
        ),
    ]
