# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0014_auto_20170727_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electronic_symmetry',
            fields=[
                ('electronic_symmetry_id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(blank=True, default='', max_length=200)),
                ('reflection_symmetry', models.CharField(blank=True, default='', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='molecular_state',
            name='electronic_symmetry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data_management.Electronic_symmetry'),
        ),
    ]
