# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0015_auto_20170801_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecular_state',
            name='electronic_symmetry',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='data_management.Electronic_symmetry'),
        ),
        migrations.AlterField(
            model_name='molecular_state',
            name='total_electronic_spin',
            field=models.IntegerField(default=0),
        ),
    ]
