# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0016_auto_20170801_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference_publication',
            name='reference_publication_tag',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
