# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-01 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0017_reference_publication_reference_publication_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diatomic_constant',
            name='source_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='data_management.Source_type'),
        ),
        migrations.AlterField(
            model_name='molecular_state',
            name='total_angular_momentum',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='molecular_state',
            name='total_electronic_spin',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
