# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-02 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0019_auto_20170801_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_publication',
            name='author',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='reference_publication',
            name='journal',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='reference_publication',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
