# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0023_auto_20170803_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_publication',
            name='number',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
