# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0026_auto_20170803_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_publication',
            name='reference_publication_tag',
            field=models.CharField(blank=True, default='', max_length=200, unique=True),
        ),
    ]
