# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0027_auto_20170803_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecular_state',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
