# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-26 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0028_auto_20170803_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_data',
            fields=[
                ('new_data_id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=200)),
            ],
        ),
    ]
