# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-26 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0029_new_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_data',
            name='cons_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='new_data',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='new_data',
            name='value',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='new_data',
            name='symbol',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
