# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-26 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0030_auto_20180726_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_data',
            name='cons_type',
        ),
        migrations.AddField(
            model_name='new_data',
            name='constant_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='data_management.Constant_type'),
        ),
        migrations.AddField(
            model_name='new_data',
            name='source_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
