# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-26 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0032_new_data_is_unsertain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_data',
            old_name='is_unsertain',
            new_name='is_uncertain',
        ),
    ]
