# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-26 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0033_auto_20180726_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_data',
            name='extra_symbol',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
