# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-26 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0034_new_data_extra_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_data',
            name='alternate_type',
            field=models.BooleanField(default=False),
        ),
    ]
